### 官方配置文档：https://pymumu.github.io/smartdns/configuration/
### 官方默认示例：https://github.com/pymumu/smartdns/blob/master/etc/smartdns/smartdns.conf
### 注意：同项配置以本文件为准，会覆盖面板设置
####################################################
## 基础配置
####################################################

# 屏蔽上游返回的无效 IP
bogus-nxdomain 127.0.0.0/8
bogus-nxdomain 0.0.0.0/8

####################################################
## 上游 DNS 服务器
## 参考：https://dns.iui.im/
####################################################

# 全局默认上游
server 223.5.5.5

## Safe 分组：国内加密 DNS
# 阿里公共 DNS DoT
server-tls 223.5.5.5:853 -blacklist-ip -spki-pin pa14rFR/bBJ25OSjCswaXu6YKWgQ2BDY5jhRRicqeik= -host-name public1.alidns.com -group Safe
# OneDNS 纯净 DoT
server-tls dot-pure.onedns.net:853 -blacklist-ip -spki-pin iga7XjWw3PbkshhBqHCsXnZxcc8ZiU919nTlPx4zhm8= -host-name dot-pure.onedns.net -group Safe
# 腾讯公共 DNS DoT
server-tls dot.pub:853 -blacklist-ip -spki-pin 5TIMjgyMhA0qmPdK+AM9LX6vNI/9EPBydh/ZXdfcYmI= -host-name dot.pub -group Safe

## oversea 分组：海外 DNS
# Cloudflare DoT
server-tls 1.1.1.1:853 -host-name cloudflare-dns.com -group oversea -exclude-default-group
# Google DoT
server-tls 8.8.8.8:853 -host-name dns.google -group oversea -exclude-default-group
# Cloudflare UDP
server 1.1.1.1 -group oversea -exclude-default-group

####################################################
## 域名分流规则
####################################################

domain-rules /github.com/ -c none -n oversea
domain-rules /githubapp.com/ -c none -n oversea
domain-rules /github.io/ -c none -n oversea
domain-rules /githubusercontent.com/ -c none -n oversea
domain-rules /gist.github.com/ -c none -n oversea
domain-rules /githubcopilot.com/ -c none -n oversea
domain-rules /api.github.com/ -c none -n oversea
domain-rules /codeload.github.com/ -c none -n oversea
domain-rules /raw.githubusercontent.com/ -c none -n oversea
domain-rules /uploads.github.com/ -c none -n oversea
domain-rules /githubassets.com/ -c none -n oversea
domain-rules /github.githubassets.com/ -c none -n oversea
domain-rules /github-cloud.s3.amazonaws.com/ -c none -n oversea
domain-rules /ghcr.io/ -c none -n oversea
